### ISSUE TITLE
Keys flying off the keyboard when colliding with another object

### ISSUE THREAD

**Issue by LucaJeevanjee** [ultraleap/XR-Keyboard#1]

**Comment by Dwarph** [comment]
Hey LucaJeevanjee - thanks for logging this, sorry for the slow reply - I forgot to watch this repo for new issues. Should be quicker in the future.

Could you provide me with more details? I've tried to recreate this using a cube with an interaction behaviour (see attached video) but no luck. 

https://user-images.githubusercontent.com/17143693/154804214-a8ce990b-3142-4454-bb02-1460c9cd7aa0.mp4

**Comment by Dwarph** [comment]
I haven't heard back from the reporter of this issue & am unable to replicate it (see the above video), so I'll close this for the moment.

**Comment by LucaJeevanjee** [comment]
Sorry was away for a while, I've been playing around with it and this only happens when you link it with the MRTK hand control so I am not sure if this is an issue on your side or theirs.

**Comment by Dwarph** [comment]
Ah interesting - I haven't attempted to use this in conjunction with MRTK. There'll definitely be some clashes between Ultraleap's tooling and MRTKs. Afraid we don't currently have plans for this KB to work with MRTK

**Comment by LucaJeevanjee** [comment]
Yeah, was trying to make this keyboard moveable to act like a real one so... if you have any ideas. I'm also trying to make a mouse!

**Comment by Dwarph** [comment]
If you want it to act like a physical object, check out our interaction engine. You could attach all the keys to a parent object, pop a collider on that & an "interaction behaviour", then you should hopefully be able to just pick it up like a physical object with your hand! 

Mouse is more interesting - I'd be interested to see if you come up with a good solution. I'd keep an eye on the preview section of our tooling if you're interested in interacting with virtual objects, we've got some fun stuff we're working on.

**Comment by LucaJeevanjee** [comment]
> If you want it to act like a physical object, check out our interaction engine. You could attach all the keys to a parent object, pop a collider on that & an "interaction behaviour", then you should hopefully be able to just pick it up like a physical object with your hand! 
> 
> Mouse is more interesting - I'd be interested to see if you come up with a good solution. I'd keep an eye on the preview section of our tooling if you're interested in interacting with virtual objects, we've got some fun stuff we're working on.

Thanks I'll give that a try!

Yeah it's proving difficult right now, especially the physics and handling..
